version: '3.4'
services:
  docker-in-docker-profiler:
    labels:
      app.name: "docker-in-docker-profiler"
      app.version: "0.0.1-9f5e6cc-dirty"
      app.build_date: "20200418131808"
      app.environment: "live"
      app.branch: "release"
    container_name: docker-in-docker-profiler
    restart: always
    privileged: true
    image: goldentigerindia/docker-in-docker-profiler:0.0.1-9f5e6cc-dirty
    environment:
      - ENVIRONMENT_NAME=live
      - BUILD_BRANCH=release
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
