version: '3.4'
services:
  docker-in-docker:
    restart: always
    privileged: true
    image: goldentigerindia/docker-in-docker-profiler:{VERSION}
    environment:
      - ENVIRONMENT_NAME={ENVIRONMENT_NAME}
      - BUILD_BRANCH={BUILD_BRANCH}
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
