version: '3.4'
services:
  docker-in-docker-profiler:
    labels:
      app.name: "docker-in-docker-profiler"
      app.version: "{VERSION}"
      app.build_date: "{DATE}"
      app.environment: "{ENVIRONMENT_NAME}"
      app.branch: "{BUILD_BRANCH}"
    container_name: docker-in-docker-profiler
    restart: always
    privileged: true
    image: goldentigerindia/docker-in-docker-profiler:{VERSION}
    environment:
      - ENVIRONMENT_NAME={ENVIRONMENT_NAME}
      - BUILD_BRANCH={BUILD_BRANCH}
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
