version: '3.4'
services:
  docker-in-docker-profiler:
    restart: always
    privileged: true
    image: goldentigerindia/docker-in-docker-profiler:0.0.1-fb7e9a7-dirty
    environment:
      - ENVIRONMENT_NAME=qa
      - BUILD_BRANCH=master
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
